var characters = [
  {
    name: "Alan Turing",
    image: "turing.jpg",
    gender: "male",
    era: "20",
    field: "STEM",
    jobs: ["matematico", "crittografo"],
    region: "Europa",
    nation_b: "UK",
    nation_d: "UK",
    samedb: true,       
  },
  {
    name: "Richard Feynman",
    image: "freyman.jpg",
    gender: "male",
    era: "20",
    field: "STEM",
    jobs: ["fisico", "divulgatore scientifico"],
    region: "Nord America",
    nation_b: "USA",
    nation_d: "USA",
    samedb: true,
    quant: true,    
    nobel: true,
  },
  {
    name: "Stephen Hawking",
    image: "hawking.jpg",
    gender: "male",
    era: "20",
    field: "STEM",
    jobs: ["fisico", "astrofisico","matematico","divulgatore scientifico"],
    region: "Europa",
    nation_b: "UK",
    nation_d: "UK",
    samedb: true,
    quant: true,    
    grav: true,
  },
  {
    name: "Albert Einstein",
    image: "einstein.jpg",
    gender: "male",
    era: "19",
    field: "STEM",
    jobs: ["fisico"],
    region: "Europa",
    nation_b: "Germania",
    nation_d: "USA",
    nobel: true,
    grav: true,  
    quant: true,
    lab: true,  
  },
  {
    name: "Albert Hoffman",
    image: "hofmann.jpg",
    gender: "male",
    era: "20",
    field: "STEM",
    jobs: ["chimico", "farmacologo"],
    region: "Europa",
    nation_b: "Svizzera",
    nation_d: "Svizzera",
    samedb: true,
  },
  {
    name: "Carl Friedrich Gauss",
    image: "gauss.jpg",
    gender: "male",
    era: "pre-19",
    field: "STEM",
    jobs: ["matematico", "astronomo", "fisico"],
    region: "Europa",
    nation_b: "Germania",
    nation_d: "Germania",
    samedb: true,
    math: true,
  },
  {
    name: "Carl Sagan",
    image: "sagan.jpg",
    gender: "male",
    era: "20",
    field: "STEM",
    jobs: ["astrofisico", "divulgatore scientifico"],
    region: "Nord America",
    nation_b: "USA",
    nation_d: "USA",
    samedb: true,
    tv: true,
  },
  {
    name: "Charles Darwin",
    image: "darwin.jpg",
    gender: "male",
    era: "19",
    field: "STEM",
    jobs: ["biologo", "esploratore", "geologo"],
    region: "Europa",
    nation_b: "UK",
    nation_d: "UK",
    samedb: true,
  },
  {
    name: "Margaret Hamilton",
    image: "hamilton.jpg",
    gender: "female",
    era: "20",
    field: "STEM",
    jobs: ["informatica"],
    region: "Nord America",
    nation_b: "USA",
    alive: true,
     os: true,   
  },
  {
    name: "Dmitrij Mendeleev",
    image: "mendeleev.jpg",
    gender: "male",
    era: "19",
    field: "STEM",
    jobs: ["chimico"],
    region: "Europa",
    nation_b: "Russia",
    nation_d: "Russia",
    samedb: true,
    elem: true,  
  
  },
  {
    name: "Enrico Fermi",
    image: "fermi.jpg",
    gender: "male",
    era: "20",
    field: "STEM",
    jobs: ["fisico"],
    region: "Europa",
    nation_b: "Italia",
    nation_d: "USA",
    nobel: true,
    progect: true,
    quant: true,
    lab: true,
  },
  {
    name: "Eulero",
    image: "eulero.jpg",
    gender: "male",
    era: "pre-19",
    field: "STEM",
    jobs: ["matematico", "fisico"],
    region: "Europa",
    nation_b: "Svizzera",
    nation_d: "Russia",
    math: true,
  },
  {
    name: "Fibonacci",
    image: "fibonacci.jpg",
    gender: "male",
    era: "pre-19",
    field: "STEM",
    jobs: ["matematico"],
    region: "Europa",
    nation_b: "Italia",
    nation_d: "Italia",
    samedb: true,
    math: true,
  },
  {
    name: "Niels Bohr",
    image: "bohr.jpg",
    gender: "male",
    era: "20",
    field: "STEM",
    jobs: ["fisico"],
    region: "Europa",
    nation_b: "Danimarca",
    nation_d: "Danimarca",
    samedb: true,
    nobel: true,
    quant: true,  
    lab: true,  
  },
  {
    name: "Alexander Fleming",
    image: "fleming.jpg",
    gender: "male",
    era: "19",
    field: "STEM",
    jobs: ["biologo", "farmacologo"],
    region: "Europa",
    nation_b: "UK",
    nation_d: "UK",
    samedb: true,
    nobel: true,
  },
  {
    name: "Nikolaus Otto",
    image: "otto.jpg",
    gender: "male",
    era: "19",
    field: "STEM",
    jobs: ["ingegnere"],
    region: "Europa",
    nation_b: "Germania",
    nation_d: "Germania",
    samedb: true,
  },
  {
    name: "Tim Berners-Lee",
    image: "bernerslee.jpg",
    gender: "male",
    era: "20",
    field: "STEM",
    jobs: ["informatica"],
    region: "Europa",
    nation_b: "UK",
    alive: true,
     os: true,   
  },
  {
    name: "Galileo Galilei",
    image: "galilei.jpg",
    gender: "male",
    era: "pre-19",
    field: "STEM",
    jobs: ["fisico", "astronomo"],
    region: "Europa",
    nation_b: "Italia",
    nation_d: "Italia",
    samedb: true,
  },
  {
    name: "Guglielmo Marconi",
    image: "marconi.jpg",
    gender: "male",
    era: "20",
    field: "STEM",
    jobs: ["ingegnere", "inventore"],
    region: "Europa",
    nation_b: "Italia",
    nation_d: "UK",
    nobel: true,
  },
  {
    name: "Isaac Newton",
    image: "newton.jpg",
    gender: "male",
    era: "pre-19",
    field: "STEM",
    jobs: ["matematico", "fisico"],
    region: "Europa",
    nation_b: "UK",
    nation_d: "UK",
    samedb: true,
    grav: true,  
  },
  {
    name: "Grace Hopper",
    image: "hopper.jpg",
    gender: "female",
    era: "20",
    field: "STEM",
    jobs: ["informatica", "ammiraglio", "matematico"],
    region: "Nord America",
    nation_b: "USA",
    nation_d: "USA",
    samedb: true,
     os: true,   
  },
  {
    name: "James Watt",
    image: "watt.jpg",
    gender: "male",
    era: "pre-19",
    field: "STEM",
    jobs: ["ingegnere"],
    region: "Europa",
    nation_b: "UK",
    nation_d: "UK",
    samedb: true,
  },
  {
    name: "John von Neumann",
    image: "newman.jpg",
    gender: "male",
    era: "20",
    field: "STEM",
    jobs: ["matematico", "informatica"],
    region: "Nord America",
    nation_b: "Ungheria",
    nation_d: "USA",
    progect: true,
    quant: true,
    lab: true,  
  },
  {
    name: "Antoine Lavoisier",
    image: "lavoisier.jpg",
    gender: "male",
    era: "pre-19",
    field: "STEM",
    jobs: ["chimico", "biologo"],
    region: "Europa",
    nation_b: "Francia",
    nation_d: "Francia",
    samedb: true,
    elem: true,
    lab: true,  
  },
  {
    name: "Marie Curie",
    image: "curie.jpg",
    gender: "female",
    era: "19",
    field: "STEM",
    jobs: ["fisico", "chimico"],
    region: "Europa",
    nation_b: "Polonia",
    nation_d: "Francia",
    nobel: true,
    elem: true,
    lab: true,  
  },
  {
    name: "Rosalind Franklin",
    image: "franklin.jpg",
    gender: "female",
    era: "20",
    field: "STEM",
    jobs: ["biofisico"],
    region: "Europa",
    nation_b: "UK",
    nation_d: "UK",
    samedb: true,
  },
  {
    name: "Neal deGrasse Tyson",
    image: "tyson.jpg",
    gender: "male",
    era: "20",
    field: "STEM",
    jobs: ["astronomo", "astrofisico","divulgatore scientifico"],
    region: "Nord America",
    nation_b: "USA",
    alive: true,
    tv: true,
  },
  {
    name: "Nikola Tesla",
    image: "tesla.jpeg",
    gender: "male",
    era: "19",
    field: "STEM",
    jobs: ["ingegnere", "inventore"],
    region: "Europa",
    nation_b: "Croazia",
    nation_d: "USA",
  },
  {
    name: "Dennis Ritchie",
    image: "richie.jpg",
    gender: "male",
    era: "20",
    field: "STEM",
    jobs: ["informatica"],
    region: "Nord America",
    nation_b: "USA",
    nation_d: "USA",
    samedb: true,
    os: true,  
  },
  {
    name: "J. Robert Oppenheimer",
    image: "oppenhaimer.jpg",
    gender: "male",
    era: "20",
    field: "STEM",
    jobs: ["fisico"],
    region: "Nord America",
    nation_b: "USA",
    nation_d: "USA",
    samedb: true,
    progect: true,
    quant: true,
  },
  // Artisti (pittori)
  {
    name: "Leonardo Da Vinci",
    image: "da_vinci.jpg",
    gender: "male",
    era: "pre-19",
    field: "Arte",
    jobs: ["pittore"],
    region: "Europa",
    nation_b: "Italia",
    nation_d: "Francia",
    movimento: "Rinascimento"
  },
  {
    name: "Caravaggio",
    image: "caravaggio.jpg",
    gender: "male",
    era: "pre-19",
    field: "Arte",
    jobs: ["pittore"],
    region: "Europa",
    nation_b: "Italia",
    nation_d: "Italia",
    samedb: true,
    movimento: "Barocco"
  },
  {
    name: "Francisco Goya",
    image: "goya.png",
    gender: "male",
    era: "pre-19",
    field: "Arte",
    jobs: ["pittore"],
    region: "Europa",
    nation_b: "Spagna",
    nation_d: "Spagna",
    samedb: true,
    movimento: "Romanticismo"
  },
  {
    name: "Frida Kahlo",
    image: "kalho.jpg",
    gender: "female",
    era: "20",
    field: "Arte",
    jobs: ["pittore"],
    region: "Nord America",
    nation_b: "Messico",
    nation_d: "Messico",
    movimento: "Surrealismo",
    samedb: true
  },
  {
    name: "Tamare de Lempica",
    image: "lempicka.jpeg",
    gender: "female",
    era: "19",
    field: "Arte",
    jobs: ["pittore"],
    region: "Europa",
    nation_b: "Polonia",
    nation_d: "Messico",
    movimento: "Art Deco"
  }
];
