var characters = [
    {
      name: "Alan Turing",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["matematico", "crittografo"],
      region: "Europa",
      nation_b: "UK",
      nation_d: "UK",
      alive: false,
      nobel: null,
    },
    {
      name: "Albert Einstein",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["fisico"],
      region: "Europa",
      nation_b: "Germany",
      nation_d: "USA",
      alive: false,
      nobel: "Fisica",
    },
    {
      name: "Albert Hoffman",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["chimico"],
      region: "Europa",
      nation_b: "Svizzera",
      nation_d: "Svizzera",
      alive: false,
      nobel: null,
    },
    {
      name: "Carl Friedrich Gauss",
      gender: "male",
      era: "pre-19",
      field: "STEM",
      jobs: ["matematico", "astronomo", "fisico"],
      region: "Europa",
      nation_b: "Sacro Romano Impero",
      nation_d: "Germania",
      alive: false,
      nobel: null,
    },
    {
      name: "Carl Sagan",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["astrofisico", "divulgatore scientifico"],
      region: "Nord America",
      nation_b: "USA",
      nation_d: "USA",
      alive: false,
      nobel: null,
    },
    {
      name: "Charles Darwin",
      gender: "male",
      era: "19",
      field: "STEM",
      jobs: ["biologo", "esploratore", "geologo"],
      region: "Europa",
      nation_b: "Regno Unito",
      nation_d: "Regno Unito",
      alive: false,
      nobel: null,
    },
    {
      name: "Margaret Hamilton",
      gender: "female",
      era: "20",
      field: "STEM",
      jobs: ["informatica"],
      region: "Nord America",
      nation_b: "USA",
      nation_d: "USA",
      alive: true,
      nobel: null,
    },
    {
      name: "Dmitrij Mendeleev",
      gender: "male",
      era: "19",
      field: "STEM",
      jobs: ["chimico"],
      region: "Europa",
      nation_b: "Russia",
      nation_d: "Russia",
      alive: false,
      nobel: null,
    },
    {
      name: "Enrico Fermi",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["fisico"],
      region: "Europa",
      nation_b: "Italia",
      nation_d: "USA",
      alive: false,
      nobel: "Fisica",
    },
    {
      name: "Leonhard Euler",
      gender: "male",
      era: "pre-19",
      field: "STEM",
      jobs: ["matematico", "fisico"],
      region: "Europa",
      nation_b: "Svizzera",
      nation_d: "Russia",
      alive: false,
      nobel: null,
    },
    {
      name: "Fibonacci",
      gender: "male",
      era: "pre-19",
      field: "STEM",
      jobs: ["matematico"],
      region: "Europa",
      nation_b: "Italia",
      nation_d: "Italia",
      alive: false,
      nobel: null,
    },
    {
      name: "Niels Bohr",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["fisico"],
      region: "Europa",
      nation_b: "Danimarca",
      nation_d: "Danimarca",
      alive: false,
      nobel: "Fisica",
    },
    {
      name: "Alexander Fleming",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["biologo", "farmacologo"],
      region: "Europa",
      nation_b: "Regno Unito",
      nation_d: "Regno Unito",
      alive: false,
      nobel: "Fisiologia o Medicina",
    },
    {
      name: "Nikolaus Otto",
      gender: "male",
      era: "19",
      field: "STEM",
      jobs: ["ingegnere"],
      region: "Europa",
      nation_b: "Germania",
      nation_d: "Germania",
      alive: false,
      nobel: null,
    },
    {
      name: "Tim Berners-Lee",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["informatica"],
      region: "Europa",
      nation_b: "Regno Unito",
      nation_d: "Regno Unito",
      alive: true,
      nobel: null,
    },
    {
      name: "Galileo Galilei",
      gender: "male",
      era: "pre-19",
      field: "STEM",
      jobs: ["fisico", "astronomo"],
      region: "Europa",
      nation_b: "Italia",
      nation_d: "Italia",
      alive: false,
      nobel: null,
    },
    {
      name: "Guglielmo Marconi",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["ingegnere", "inventore"],
      region: "Europa",
      nation_b: "Italia",
      nation_d: "Regno Unito",
      alive: false,
      nobel: "Fisica",
    },
    {
      name: "Isaac Newton",
      gender: "male",
      era: "pre-19",
      field: "STEM",
      jobs: ["matematico", "fisico"],
      region: "Europa",
      nation_b: "Regno Unito",
      nation_d: "Regno Unito",
      alive: false,
      nobel: null,
    },
    {
      name: "Grace Hopper",
      gender: "female",
      era: "20",
      field: "STEM",
      jobs: ["informatica", "ammiraglio"],
      region: "Nord America",
      nation_b: "USA",
      nation_d: "USA",
      alive: false,
      nobel: null,
    },
    {
      name: "James Watt",
      gender: "male",
      era: "18",
      field: "STEM",
      jobs: ["ingegnere"],
      region: "Europa",
      nation_b: "Regno Unito",
      nation_d: "Regno Unito",
      alive: false,
      nobel: null,
    },
    {
      name: "John von Neumann",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["matematico", "informatica"],
      region: "Nord America",
      nation_b: "Ungheria",
      nation_d: "USA",
      alive: false,
      nobel: null,
    },
    {
      name: "Antoine Lavoisier",
      gender: "male",
      era: "18",
      field: "STEM",
      jobs: ["chimico"],
      region: "Europa",
      nation_b: "Francia",
      nation_d: "Francia",
      alive: false,
      nobel: null,
    },
    {
      name: "Marie Curie",
      gender: "female",
      era: "20",
      field: "STEM",
      jobs: ["fisico", "chimico"],
      region: "Europa",
      nation_b: "Polonia",
      nation_d: "Francia",
      alive: false,
      nobel: "Fisica",
    },
    {
      name: "Rosalind Franklin",
      gender: "female",
      era: "20",
      field: "STEM",
      jobs: ["biofisico"],
      region: "Europa",
      nation_b: "Regno Unito",
      nation_d: "Regno Unito",
      alive: false,
      nobel: null,
    },
    {
      name: "Neal deGrasse Tyson",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["astronomo", "astrofisico"],
      region: "Nord America",
      nation_b: "USA",
      nation_d: "USA",
      alive: true,
      nobel: null,
    },
    {
      name: "Nikola Tesla",
      gender: "male",
      era: "19",
      field: "STEM",
      jobs: ["ingegnere", "inventore"],
      region: "Europa",
      nation_b: "Austria-Ungheria",
      nation_d: "USA",
      alive: false,
      nobel: "Fisica",
    },
    {
      name: "Dennis Ritchie",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["informatica"],
      region: "Nord America",
      nation_b: "USA",
      nation_d: "USA",
      alive: false,
      nobel: null,
    },
    {
      name: "J. Robert Oppenheimer",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["fisico"],
      region: "Nord America",
      nation_b: "USA",
      nation_d: "USA",
      alive: false,
      nobel: null,
    },
    // Artisti (pittori)
    {
      name: "Leonardo Da Vinci",
      gender: "male",
      era: "pre-19",
      field: "Arte",
      jobs: ["pittore"],
      region: "Europa",
      nation_b: "Italia",
      nation_d: "Italia",
      alive: false,
      nobel: null,
      tecnic: "Pittura Rinascimentale"
    },
    {
      name: "Caravaggio",
      gender: "male",
      era: "pre-19",
      field: "Arte",
      jobs: ["pittore"],
      region: "Europa",
      nation_b: "Italia",
      nation_d: "Italia",
      alive: false,
      nobel: null,
      tecnic: "Pittura Barocca"
    },
    {
      name: "Francisco Goya",
      gender: "male",
      era: "pre-19",
      field: "Arte",
      jobs: ["pittore"],
      region: "Europa",
      nation_b: "Spagna",
      nation_d: "Spagna",
      alive: false,
      nobel: null,
      tecnic: "Romanticismo, Pittura Barocca"
    },
    {
      name: "Frida Kahlo",
      gender: "female",
      era: "20",
      field: "Arte",
      jobs: ["pittore"],
      region: "Nord America",
      nation_b: "Messico",
      nation_d: "Messico",
      alive: false,
      nobel: null,
      tecnic: "Pittura Surrealista"
    },
    {
      name: "Pablo Picasso",
      gender: "male",
      era: "20",
      field: "Arte",
      jobs: ["pittore"],
      region: "Europa",
      nation_b: "Spagna",
      nation_d: "Francia",
      alive: false,
      nobel: null,
      tecnic: "Cubismo"
    }
  ];
  