var characters = [
    {
      name: "Alan Turing",
      image: "../img/turing.jpg",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["matematico", "crittografo"],
      region: "Europa",
      nation_b: "UK",
      nation_d: "UK",
      samedb: true,
      alive: false,
      tv: false,  
    },
    {
      name: "Richard Feynman",
      image: "../img/freyman.jpg",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["fisico", "divulgatore scientifico"],
      region: "Nord America",
      nation_b: "USA",
      nation_d: "USA",
      samedb: true,
      alive: false,
      tv: true,
    },
    {
      name: "Stephen Hawking",
      image: "../img/hawking.jpg",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["fisico", "astrofisico","matematico","divulgatore scientifico"],
      region: "Europa",
      nation_b: "UK",
      nation_d: "UK",
      samedb: true,
      alive: false,
      tv: true,
    },
    {
      name: "Albert Einstein",
      image: "../img/einstein.jpg",
      gender: "male",
      era: "19",
      field: "STEM",
      jobs: ["fisico"],
      region: "Europa",
      nation_b: "Germania",
      nation_d: "USA",
        samedb: false,
      alive: false,
      nobel: true,
    },
    {
      name: "Albert Hoffman",
      image: "../img/hofmann.jpg",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["chimico"],
      region: "Europa",
      nation_b: "Svizzera",
      nation_d: "Svizzera",
      samedb: true,
      alive: false,
      tv: true,
        nobel: false,
    },
    {
      name: "Carl Friedrich Gauss",
      image: "../img/gauss.jpg",
      gender: "male",
      era: "pre-19",
      field: "STEM",
      jobs: ["matematico", "astronomo", "fisico"],
      region: "Europa",
      nation_b: "Germania",
      nation_d: "Germania",
      samedb: true,
      alive: false,
    },
    {
      name: "Carl Sagan",
      image: "../img/sagan.jpg",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["astrofisico", "divulgatore scientifico"],
      region: "Nord America",
      nation_b: "USA",
      nation_d: "USA",
      samedb: true,
      alive: false,
      tv: true,
    },
    {
      name: "Charles Darwin",
      image: "../img/darwin.jpg",
      gender: "male",
      era: "19",
      field: "STEM",
      jobs: ["biologo", "esploratore", "geologo"],
      region: "Europa",
      nation_b: "UK",
      nation_d: "UK",
      samedb: true,
      alive: false,
    },
    {
      name: "Margaret Hamilton",
      image: "../img/hamilton.jpg",
      gender: "female",
      era: "20",
      field: "STEM",
      jobs: ["informatica"],
      region: "Nord America",
      nation_b: "USA",
      alive: true,
    },
    {
      name: "Dmitrij Mendeleev",
      image: "../img/mendeleev.jpg",
      gender: "male",
      era: "19",
      field: "STEM",
      jobs: ["chimico"],
      region: "Europa",
      nation_b: "Russia",
      nation_d: "Russia",
      samedb: true,
      alive: false,
    },
    {
      name: "Enrico Fermi",
      image: "../img/fermi.jpg",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["fisico"],
      region: "Europa",
      nation_b: "Italia",
      nation_d: "USA",
      alive: false,
      nobel: true,
      progect: true,
    },
    {
      name: "Eulero",
      image: "../img/eulero.jpg",
      gender: "male",
      era: "pre-19",
      field: "STEM",
      jobs: ["matematico", "fisico"],
      region: "Europa",
      nation_b: "Svizzera",
      nation_d: "Russia",
      alive: false,
    },
    {
      name: "Fibonacci",
      image: "../img/fibonacci.jpg",
      gender: "male",
      era: "pre-19",
      field: "STEM",
      jobs: ["matematico"],
      region: "Europa",
      nation_b: "Italia",
      nation_d: "Italia",
      samedb: true,
      alive: false,
    },
    {
      name: "Niels Bohr",
      image: "../img/bohr.jpg",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["fisico"],
      region: "Europa",
      nation_b: "Danimarca",
      nation_d: "Danimarca",
      samedb: true,
      alive: false,
      nobel: true,
    },
    {
      name: "Alexander Fleming",
      image: "../img/fleming.jpg",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["biologo", "farmacologo"],
      region: "Europa",
      nation_b: "UK",
      nation_d: "UK",
      samedb: true,
      alive: false,
      nobel: true,
    },
    {
      name: "Nikolaus Otto",
      image: "../img/otto.jpg",
      gender: "male",
      era: "19",
      field: "STEM",
      jobs: ["ingegnere"],
      region: "Europa",
      nation_b: "Germania",
      nation_d: "Germania",
      samedb: true,
      alive: false,
    },
    {
      name: "Tim Berners-Lee",
      image: "../img/bernerslee.jpg",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["informatica"],
      region: "Europa",
      nation_b: "UK",
      alive: true,
    },
    {
      name: "Galileo Galilei",
      image: "../img/galilei.jpg",
      gender: "male",
      era: "pre-19",
      field: "STEM",
      jobs: ["fisico", "astronomo"],
      region: "Europa",
      nation_b: "Italia",
      nation_d: "Italia",
      samedb: true,
      alive: false,
    },
    {
      name: "Guglielmo Marconi",
      image: "../img/marconi.jpg",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["ingegnere", "inventore"],
      region: "Europa",
      nation_b: "Italia",
      nation_d: "UK",
      alive: false,
      nobel: true,
    },
    {
      name: "Isaac Newton",
      image: "../img/newton.jpg",
      gender: "male",
      era: "pre-19",
      field: "STEM",
      jobs: ["matematico", "fisico"],
      region: "Europa",
      nation_b: "UK",
      nation_d: "UK",
      samedb: true,
      alive: false, 
    },
    {
      name: "Grace Hopper",
      image: "../img/hopper.jpg",
      gender: "female",
      era: "20",
      field: "STEM",
      jobs: ["informatica", "ammiraglio"],
      region: "Nord America",
      nation_b: "USA",
      nation_d: "USA",
      samedb: true,
      alive: false,
    },
    {
      name: "James Watt",
      image: "../img/watt.jpg",
      gender: "male",
      era: "pre-19",
      field: "STEM",
      jobs: ["ingegnere"],
      region: "Europa",
      nation_b: "UK",
      nation_d: "UK",
      samedb: true,
      alive: false,
    },
    {
      name: "John von Neumann",
      image: "../img/newman.jpg",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["matematico", "informatica"],
      region: "Nord America",
      nation_b: "Ungheria",
      nation_d: "USA",
      alive: false,
      progect: true,
    },
    {
      name: "Antoine Lavoisier",
      image: "../img/lavoisier.jpg",
      gender: "male",
      era: "pre-19",
      field: "STEM",
      jobs: ["chimico", "biologo"],
      region: "Europa",
      nation_b: "Francia",
      nation_d: "Francia",
      samedb: true,
      alive: false,
    },
    {
      name: "Marie Curie",
      image: "../img/curie.jpg",
      gender: "female",
      era: "20",
      field: "STEM",
      jobs: ["fisico", "chimico"],
      region: "Europa",
      nation_b: "Polonia",
      nation_d: "Francia",
      alive: false,
      nobel: true,
    },
    {
      name: "Rosalind Franklin",
      image: "../img/franklin.jpg",
      gender: "female",
      era: "20",
      field: "STEM",
      jobs: ["biofisico"],
      region: "Europa",
      nation_b: "UK",
      nation_d: "UK",
      samedb: true,
      alive: false,
    },
    {
      name: "Neal deGrasse Tyson",
      image: "../img/tyson.jpg",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["astronomo", "astrofisico","divulgatore scientifico"],
      region: "Nord America",
      nation_b: "USA",
      alive: true,
      tv: true,
    },
    {
      name: "Nikola Tesla",
      image: "../img/tesla.jpeg",
      gender: "male",
      era: "19",
      field: "STEM",
      jobs: ["ingegnere", "inventore"],
      region: "Europa",
      nation_b: "Croazia",
      nation_d: "USA",
      alive: false,
      nobel: false,
    },
    {
      name: "Dennis Ritchie",
      image: "../img/richie.jpg",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["informatica"],
      region: "Nord America",
      nation_b: "USA",
      nation_d: "USA",
      samedb: true,
      alive: false,
    },
    {
      name: "J. Robert Oppenheimer",
      image: "../img/oppenhaimer.jpg",
      gender: "male",
      era: "20",
      field: "STEM",
      jobs: ["fisico"],
      region: "Nord America",
      nation_b: "USA",
      nation_d: "USA",
      samedb: true,
      alive: false,
      progect: true,
    },
    // Artisti (pittori)
    {
      name: "Leonardo Da Vinci",
      image: "../img/da_vinci.jpg",
      gender: "male",
      era: "pre-19",
      field: "Arte",
      jobs: ["pittore"],
      region: "Europa",
      nation_b: "Italia",
      nation_d: "Francia",
      samedb: false,
      alive: false,
      movimento: "Rinascimento"
    },
    {
      name: "Caravaggio",
      image: "../img/caravaggio.jpg",
      gender: "male",
      era: "pre-19",
      field: "Arte",
      jobs: ["pittore"],
      region: "Europa",
      nation_b: "Italia",
      nation_d: "Italia",
      samedb: true,
      alive: false,
      movimento: "Barocco"
    },
    {
      name: "Francisco Goya",
      image: "../img/goya.png",
      gender: "male",
      era: "pre-19",
      field: "Arte",
      jobs: ["pittore"],
      region: "Europa",
      nation_b: "Spagna",
      nation_d: "Spagna",
      samedb: true,
      alive: false,
      movimento: "Romanticismo"
    },
    {
      name: "Frida Kahlo",
      image: "../img/kalho.jpg",
      gender: "female",
      era: "20",
      field: "Arte",
      jobs: ["pittore"],
      region: "Nord America",
      nation_b: "Messico",
      nation_d: "Messico",
      alive: false,
      movimento: "Surrealismo",
      samedb: true
    },
    {
      name: "Tamare de Lempica",
      image: "../img/lempicka.jpeg",
      gender: "female",
      era: "20",
      field: "Arte",
      jobs: ["pittore"],
      region: "Europa",
      nation_b: "Polonia",
      nation_d: "Messico",
      alive: false,
      movimento: "Art Deco"
    }
  ];
  
